export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as Account } from './Account'
export { default as TvShows } from './TvShows'
export { default as Movie } from './Movie'
export { default as TvShowCard } from './TvShowCard'
