export { default as Navbar } from './Navbar'
export { default as Main } from './Main'
export { default as Row } from './Row'
export { default as Movies } from './Movies'
export { default as FavShows } from './FavShows'
export { default as Footer } from './Footer'
